### PR TITLE
Removed user-scalable="no"

### PR DESCRIPTION
**Pull request by nfolkman**
Removed user-scalable="no" for Accessibility reasons.

### CODE REVIEW

**Comment by floorrinse** [comment]
You also need to add this for the `index.html` and `contributors.html` pages

**Comment by nfolkman** [comment]
@floorrinse  I'm pretty sure `index.html` and `contributors.html` are already user-scalable since they don't have the `user-scalable` attribute at all. Is that what you were meaning?

**Comment by 20jasper** [comment]
Yep, by default, user scalability is allowed, so you can just delete the attribute entirely

**Comment by floorrinse** [comment]
> @floorrinse I'm pretty sure `index.html` and `contributors.html` are already user-scalable since they don't have the `user-scalable` attribute at all. Is that what you were meaning?

Ah ok I didn't check those pages beforehand so I assumed this `user-scalable=no"` code was still in those pages. Sorry for the confusing comment!

**Comment by nfolkman** [comment]
> > @floorrinse I'm pretty sure `index.html` and `contributors.html` are already user-scalable since they don't have the `user-scalable` attribute at all. Is that what you were meaning?
> 
> Ah ok I didn't check those pages beforehand so I assumed this `user-scalable=no"` code was still in those pages. Sorry for the confusing comment!

No worries!

**Pull request merged**
