### PR TITLE
Added logo picture to images folder

### PR DESCRIPTION
**Pull request by DekotaNelson**
This is the #8 logo that had majority vote. I haven't done anything with it, just added the file to the images folder. Haven't been able to participate as much the past day or two, but wanted to go ahead and add the file in case anyone wants to use it. I'm hoping to be able to help more this week.

### CODE REVIEW

**Comment by floorrinse** [comment]
Is there a way to get the png or svg of this image? it's not a dealbreaker but jpg is lower quality and won't scale. i think this is fine tho if there isnt any other option 👍

**Comment by 20jasper** [comment]
You can always convert to png, but I prefer webp most of the time (and jpeg when it looks bad). I tried avif a while ago, but it didn't work on mobile

**Comment by 20jasper** [comment]
Also @floorrinse, how big do we need to scale it? I think we'd just be using it at the size of the gem icon, so it shouldn't matter too much right?

**Comment by floorrinse** [comment]
> Also @floorrinse, how big do we need to scale it? I think we'd just be using it at the size of the gem icon, so it shouldn't matter too much right?

My bad, I thought it was a banner type of image that would take up about the pink-dotted space noted in below image:
Screen Shot 2022-04-04 at 11 23 48 PM

If it's just replacing that lil gem icon, then youre right it shouldnt matter about scaling

**Pull request merged**
